name: Multiple Steps 

on:
  push:

jobs:
  practice-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show Date 
        run: date
        
      - name: Show Directory 
        run: pwd
        
      - name: Show current User
        run: whoami 
        
      - name: List file
        run: ls -la
